---
name: Create upstream pull request
on:
  pull_request:
    branches:
      - release_*
    types: [closed]

jobs:
  if: github.event.pull_request.merged == true && contains(github.event.comment.body, '/bug-fix-release-train')
  generate-matrix:
    name: Generate matrix for pull requests
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set matrix for build
        id: set-matrix
        run: |
          (( $(( (`date +\%s` / 604800 + 1) % 2 )) )) && matrix=$(node scripts/upstream.js)
          echo "::set-output name=matrix::$( echo "$matrix" )"
  pull-request:
    name: Pull Request to Upstream Release "${{ matrix.upstream_release }}"
    needs: generate-matrix
    strategy:
      matrix: ${{fromJson(needs.generate-matrix.outputs.matrix)}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pull-request
        if:   ${{ matrix.upstream_release }} != ''
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: ${{ matrix.upstream_release }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Pulling ${{ github.ref }} into ${{ matrix.upstream_release }} "
          pr_body: "*An automated PR for Release Train Branch ${{ matrix.upstream_release }} * "
          pr_reviewer: "mluedke2,sejalbiren"
          pr_assignee: "mluedke2,sejalbiren"

